export const tableData = [
  {
    id: 1,
    surname: "Фввв",
    name: "Юпноне",
    patronymic: "Зььл",
    hbty: "15.10.1989",
    history: "5",
    philosophy: "5",
    informatics: "5",
    economics: "5",
    physics: "5",
  },

  {
    id: 2,
    surname: "Aалабина",
    name: "Элия",
    patronymic: "Ивановна",
    hbty: "10.10.1989",
    history: "2",
    philosophy: "5",
    informatics: "5",
    economics: "5",
    physics: "5",
  },
  {
    id: 3,
    surname: "Оллабина",
    name: "Хия",
    patronymic: "Про",
    hbpatronymicty: "15.10.1902",
    history: "5",
    philosophy: "4",
    informatics: "2",
    economics: "5",
    physics: "5",
  },
  {
    id: 4,
    surname: "Нлоабина",
    name: "Ваапа",
    patronymic: "Опрва",
    hbty: "20.10.1989",
    history: "4",
    philosophy: "5",
    informatics: "4",
    economics: "5",
    physics: "5",
  },
  {
    id: 5,
    surname: "Крро",
    name: "Шлбю",
    patronymic: "Впроллд",
    hbty: "20.11.1989",
    history: "5",
    philosophy: "5",
    informatics: "5",
    economics: "5",
    physics: "5",
  },
];
